

###GET Home page



GET http://localhost:3001/home


###GET login page

GET http://localhost:3001/api/login


###
GET http://localhost:3001/api/books/all
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTIwYTc2OTU1OTQyMjVjN2JkODdlYyIsImlhdCI6MTY3NTc3NTQ1MSwiZXhwIjoxNjc4MzY3NDUxfQ.yYWM1jPb7JBREGdLIwCEsuWwyWI_yRSdIaL_Y6UE0lg

###
GET http://localhost:3001/api/books/fantasy
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTIwYTc2OTU1OTQyMjVjN2JkODdlYyIsImlhdCI6MTY3NTc3NTQ1MSwiZXhwIjoxNjc4MzY3NDUxfQ.yYWM1jPb7JBREGdLIwCEsuWwyWI_yRSdIaL_Y6UE0lg


###
GET http://localhost:3001/api/books/mod
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZTIwYTc2OTU1OTQyMjVjN2JkODdlYyIsImlhdCI6MTY3NTc3NTQ1MSwiZXhwIjoxNjc4MzY3NDUxfQ.yYWM1jPb7JBREGdLIwCEsuWwyWI_yRSdIaL_Y6UE0lg

### POST to add a card:
POST http://localhost:3001/api/cards
Content-Type: application/json

{
    "name": "Pizza Dominos",
    "description": "Best Pizza in some place",
    "address": "some place",
    "phone": "050-5050022",
    "image":"http://abc.com/image.png",
    "bizNumber":1233123123
}

### GET all cards  תראה לי את כל הקלפים שיש לאחר הפוסט
GET http://localhost:3001/api/cards


### GET all students:
GET http://localhost:3001/api/students

###POST to add a student:
POST http://localhost:3001/api/students
Content-Type: application/json

{
    "firstName":"Bruce", 
    "lastName":"Wayne",
    "email":"Batman@Batcave.com"
}




###POST to add student sign up:
POST http://localhost:3001/api/auth/signup
Content-Type: application/json

{
    "username":"Edi", 
    "email":"Ed@Batcave.com",
    "password":"edBu@123!g"
}

###POST to sign in user:
POST http://localhost:3001/api/auth/signin
Content-Type: application/json
Authorization: YOUR_JWT_TOKEN

{
    "email":"Ed@Batcave.com",
    "password":"edBu@123!g"
}

# דבר ראשון עושים לוגין , מקבלים טוקן ואחרי זה מוסיפים אותו לגאט באוטורזישן